data:
  dataset_csv: D:\\Angio\\ANGIO-LSTM\\CSV_experimental.csv
  data_path: "D:\\date=angiografii - Copy\\data\\data"
  annotation: clipping_points.json
  pretrained_net: "D:\\Angio\\ANGIO-LSTM\\Experimente\\my_model05182023_0622_e350.pt"
  parent_dir_exp: "D:\\Angio\\ANGIO-LSTM\\Experimente\\Experiment_Dice_index01282024_1514"
  test_model_checkpoint: "D:\\Angio\\ANGIO-LSTM\\Experimente\\Experiment_Dice_index01282024_1514\\Weights\\epoch=594-step=227290.ckpt"
  img_size: [512,512]
  nr_frames: 12 
  split_per:
    train: 0.8
    valid: 0.1
    test: 0.1

train:
  bs: 16
  lr: 0.001
  opt: Adam
  net: GRU
  epochs: 1200
  rotate_prob: 0.5
  rotate_range: 35 
  clip_limit: 4
  tile_grid_size: [8, 8] 
  p_clahe: 0.5
  blur_limit: [1, 3] 
  sigma_limit: 0
  p_gauss_blur: 0.5
  gamma_limit: [80, 120]
  p: 0.5
  coarse_max_holes: 10
  coarse_max_height: 10
  coarse_max_width: 10
  fill_value: 0
  b_limit: 5




test:
  threshold: 0.5
